# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manager', '0003_auto_20170723_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='celery_task_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
