# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manager', '0004_todotask_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='celery_task_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
